### PR TITLE
sync create-react-app's upstream

### PR DESCRIPTION
**Pull request by endel**
Hi @wmonk, 

I've just merged `create-react-app`'s upstream and I'm sending it as a pull-request for you. The latest version support using sass/scss as CSS preprocessors. It would be a great addition here too. (https://github.com/facebook/create-react-app/pull/4195)

Let me know if this works for you. Cheers

### CODE REVIEW

**Comment by Mukhametvaleev** [comment]
20 days passed. What's wrong with this PR?

**Comment by camflan** [comment]
Is this repo still alive?

**Comment by wmonk** [comment]
No. I need to archive it again. Just unarchived to add the deprecation notice.

**Comment by endel** [comment]
Apparently `react-scripts` now supports TypeScript https://facebook.github.io/create-react-app/docs/adding-typescript

**Comment by itskibo** [comment]
@wmonk I don't think it is a good idea to mark this package as deprecated yet, as there are still some issues with the TypeScript support in CRA that this fork doesn't have.

For my use case, it's using absolute paths properly: https://github.com/facebook/create-react-app/issues/5645

**Pull request closed without merging**
